---
name: 'LuxAction'
description: 'Install the Lux package manager for Lua'
author: 'Marc Jakobi'
branding:
  color: 'purple'
  icon: 'moon'
inputs:
  version:
    description: |
      Version of Lux to install (e.g. "1.2.3" or "latest")
    required: false
    default: 'latest'
  token:
    description: |
      GitHub token for fetching Lux releases, defaults to using secrets.GITHUB_TOKEN
    required: false
    default: ${{ github.token }}
runs:
  using: 'node24'
  main: dist/index.js
  post: 'dist/index_post.js'
