---
name: 'Nix flake checks'
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    name: Nix flake checks
    runs-on: ubuntu-24.04
    permissions:
      id-token: 'write'
      contents: 'read'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: lumen-labs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run checks
        run: nix flake check -Lv
